"""Markdown builders for the documents committed under ``docs/``.

These are generated, not written. A season moves every week, so a hand-written
team report is wrong within a matchday; regenerating is one command, and the
numbers in the repository can always be traced to a run of this code.

Both documents come in English and Japanese from the same data, which is the
cheap half of bilingual docs: only prose has to be translated by hand.
"""

from datetime import datetime, timezone

from . import analysis, metrics, privacy

LABELS = {
    "en": {
        "teams_title": "Team profiles",
        "teams_intro": (
            "Every club in the division, from the federation's published match records. "
            "Aggregates only — no individual appears in this document; see "
            "[DATA_POLICY.md](DATA_POLICY.md)."
        ),
        "snapshot": "Snapshot of {series}, generated {when}. Regenerate with `{command}`.",
        "in_progress": "**Season in progress: {done} of {total} fixtures played.**",
        "table": "League table",
        "fingerprints": "Fingerprints",
        "fingerprint_note": (
            "Six indices, each scaled within this division. The chart is the same one the "
            "dashboard draws; the numbers under each club repeat it in text."
        ),
        "axes": "Indices",
        "grades": "By academic year",
        "history": "Season history",
        "history_note": "Followed by federation club id, so a division change is a real move.",
        "opponents": "Where the goals came from",
        "no_history": "No earlier season in this federation's leagues.",
        "cols_table": ["#", "Team", "P", "Pts", "W-D-L", "GF", "GA", "GD", "Shots", "S/game", "Conv"],
        "cols_grade": ["Year", "Players", "Minutes", "Goals"],
        "cols_history": ["Season", "Division", "P", "W-D-L", "Pts", "Pts/game", "GF", "GD"],
        "cols_player": ["Player", "Team", "Yr", "Pos", "Apps", "Starts", "Min", "Shots",
                        "Goals", "S/90", "G/S"],
        "summary": ("{played} played · {points} points · {gf} scored, {ga} conceded · "
                    "{spg} shots per game at {conv} · {used} players used, "
                    "top eleven took {core} of the minutes · mean year {grade}"),
        "opp_line": "{top} against the top half, {bottom} against the bottom half ({share} from below).",
        "players_title": "Player-level output — worked sample",
        "players_intro": (
            "This is what the player-level views produce. **Every club, player and result "
            "below is invented**, generated by `togakuren.sample` and put through the "
            "ordinary ingest, so the output is made by the same code path as the real thing.\n\n"
            "The real equivalent is not published, and that is deliberate rather than a "
            "limitation of the tool: the people in the federation's records are amateur "
            "students, and per-player rows are personal data. "
            "[DATA_POLICY.md](DATA_POLICY.md) has the reasoning and the measurements."
        ),
        "players_heading": "Season totals and rates",
        "players_note": (
            "Minimum {minutes} minutes. Minutes played are reconstructed from lineups, "
            "timed substitutions and dismissals — the federation records none of them."
        ),
        "minutes_heading": "Minutes by matchday",
        "minutes_note": (
            "One row per player, one column per matchday, for the club shown. A settled "
            "side is a solid block; a rotated one is patchy. The dashboard draws this as "
            "a heat map."
        ),
        "reproduce": "Reproduce",
    },
    "ja": {
        "teams_title": "チーム分析",
        "teams_intro": (
            "連盟が公開している試合記録から、その部の全チーム。集計値のみで、"
            "個人は一切登場しない（[DATA_POLICY.md](DATA_POLICY.md)）。"
        ),
        "snapshot": "{series} のスナップショット。生成 {when}。再生成は `{command}`。",
        "in_progress": "**シーズン進行中: {total}試合中{done}試合を消化。**",
        "table": "順位表",
        "fingerprints": "チームの個性",
        "fingerprint_note": (
            "6指標をこの部の中で相対化した値。図はダッシュボードと同じもので、"
            "各クラブの節に同じ数値を文字でも載せている。"
        ),
        "axes": "指標",
        "grades": "学年別",
        "history": "過去シーズン",
        "history_note": "連盟のクラブIDで追跡しているため、部の移動が実際の昇降格を表す。",
        "opponents": "得点した相手",
        "no_history": "この連盟のリーグでは過去シーズンなし。",
        "cols_table": ["#", "チーム", "試合", "勝点", "勝-分-敗", "得点", "失点", "得失",
                       "シュート", "S/試合", "決定率"],
        "cols_grade": ["学年", "人数", "出場分", "得点"],
        "cols_history": ["年度", "部", "試合", "勝-分-敗", "勝点", "1試合平均", "得点", "得失"],
        "cols_player": ["選手", "チーム", "学年", "Pos", "出場", "先発", "分", "シュート",
                        "得点", "S/90", "決定率"],
        "summary": ("{played}試合 · 勝点{points} · {gf}得点 {ga}失点 · "
                    "1試合{spg}本を決定率{conv} · {used}人起用、主力11人が出場時間の{core} · "
                    "平均学年{grade}"),
        "opp_line": "上位半分から{top}点、下位半分から{bottom}点（下位比率{share}）。",
        "players_title": "選手単位の出力 — サンプル",
        "players_intro": (
            "選手単位のビューが何を出すかを示すサンプル。**以下のクラブ・選手・結果はすべて架空**で、"
            "`togakuren.sample` が生成したものを通常のingestに通している。"
            "つまり実データと同じコード経路で作られた出力である。\n\n"
            "実データ版を公開しないのはツールの制約ではなく設計上の判断による。"
            "連盟の記録に載っているのはアマチュアの学生であり、選手単位の行は個人情報にあたる。"
            "根拠と実測値は [DATA_POLICY.md](DATA_POLICY.md) に置いてある。"
        ),
        "players_heading": "シーズン通算と率",
        "players_note": (
            "{minutes}分以上。出場時間はスタメン・交代・退場から復元した値で、"
            "連盟はいずれも記録していない。"
        ),
        "minutes_heading": "節ごとの出場時間",
        "minutes_note": (
            "1行が選手、1列が節。固定メンバーのチームは塊になり、入れ替えの多いチームはまばらになる。"
            "ダッシュボードではこれをヒートマップで描いている。"
        ),
        "reproduce": "再現手順",
    },
}


def _table(headers, rows, left=1):
    """A Markdown table. ``left`` columns are left-aligned, the rest right."""
    align = ["---"] * left + ["--:"] * (len(headers) - left)
    lines = ["| " + " | ".join(str(h) for h in headers) + " |",
             "| " + " | ".join(align) + " |"]
    for row in rows:
        lines.append("| " + " | ".join("-" if v is None else str(v) for v in row) + " |")
    return "\n".join(lines)


def _pct(value):
    return f"{value * 100:.0f}%"


def team_profiles(conn, series_id, lang="en", figure="figures/fig-fingerprints.png"):
    """The whole division: table, fingerprints and one section per club."""
    text = LABELS[lang]
    series = conn.execute("SELECT * FROM series WHERE id = ?", (series_id,)).fetchone()
    if series is None:
        raise ValueError(f"series {series_id!r} is not in this database")

    profile = analysis.team_profile(conn, series_id)
    if not profile:
        raise ValueError(f"series {series_id!r} has no completed fixtures")
    prints = {row["team_pk"]: row["axes"] for row in analysis.fingerprints(conn, series_id, profile)}
    opponents = {row["team_pk"]: row for row in analysis.goals_by_opponent(conn, series_id, profile)}
    fixtures = conn.execute(
        "SELECT COUNT(*), SUM(game_over) FROM games WHERE series_id = ?", (series_id,)
    ).fetchone()

    when = datetime.now(timezone.utc).astimezone().strftime("%Y-%m-%d")
    parts = [
        f"# {text['teams_title']} — {series['name'].strip()}",
        "",
        text["teams_intro"],
        "",
        text["snapshot"].format(
            series=f"{series['year']} {series['short_name']}", when=when,
            command=f'togakuren profiles --series "{series["year"]} {series["short_name"]}"',
        ),
    ]
    if fixtures[0] and (fixtures[1] or 0) < fixtures[0]:
        parts += ["", text["in_progress"].format(done=fixtures[1] or 0, total=fixtures[0])]

    parts += ["", f"## {text['table']}", "", _table(
        text["cols_table"],
        [
            [row["rank"], row["team"], row["played"], row["points"],
             f"{row['win']}-{row['draw']}-{row['lose']}",
             row["goals_for"], row["goals_against"], row["goal_difference"],
             row["shots"], f"{row['shots_per_game']:.1f}", f"{row['conversion']:.3f}"]
            for row in profile
        ],
        left=2,
    )]

    parts += ["", f"## {text['fingerprints']}", "", f"![{text['fingerprints']}]({figure})", "",
              text["fingerprint_note"]]

    axis_names = {key: label for key, label, _ in analysis.FINGERPRINT_AXES}
    for row in profile:
        axes = prints.get(row["team_pk"], {})
        parts += [
            "", f"### {row['rank']}. {row['team']}", "",
            text["summary"].format(
                played=row["played"], points=row["points"], gf=row["goals_for"],
                ga=row["goals_against"], spg=f"{row['shots_per_game']:.1f}",
                conv=f"{row['conversion']:.3f}", used=row["players_used"],
                core=_pct(row["core_share"]), grade=f"{row['mean_grade']:.2f}",
            ),
            "",
            "**" + text["axes"] + "** — " + " / ".join(
                f"{axis_names[key]} {axes.get(key, 0):.0f}" for key, _, _ in analysis.FINGERPRINT_AXES
            ),
        ]
        opponent = opponents.get(row["team_pk"])
        if opponent:
            parts += ["", text["opp_line"].format(
                top=opponent["vs_top"], bottom=opponent["vs_bottom"],
                share=_pct(opponent["bottom_share"]))]

        grade_rows = [
            [f"{grade}", row["grades"][grade]["players"], row["grades"][grade]["minutes"],
             row["grades"][grade]["goals"]]
            for grade in analysis.GRADES
        ]
        parts += ["", f"**{text['grades']}**", "", _table(text["cols_grade"], grade_rows)]

        history = analysis.team_history(conn, row["team_id"]) if row["team_id"] else []
        if len(history) > 1:
            parts += ["", f"**{text['history']}**", "", _table(
                text["cols_history"],
                [[h["year"], h["division"], h["played"],
                  f"{h['win']}-{h['draw']}-{h['lose']}", h["points"],
                  h.get("points_per_game"), h["goals_for"], h["goal_difference"]]
                 for h in history],
                left=2,
            )]

    parts += ["", "---", "", f"*{text['history_note']}*", ""]
    return "\n".join(parts)


def player_document(conn, series_id, lang="en", min_minutes=270, top=25, matrix_team=None):
    """The player-level output, for a database whose people are fictional."""
    text = LABELS[lang]
    series = conn.execute("SELECT * FROM series WHERE id = ?", (series_id,)).fetchone()
    names = dict(conn.execute("SELECT player_id, name FROM players"))
    rows = metrics.player_season(conn, series_id, min_minutes=min_minutes)
    profile = analysis.team_profile(conn, series_id)

    parts = [
        f"# {text['players_title']}", "", text["players_intro"], "",
        f"Source series: *{series['name'].strip()}* — "
        f"{len(profile)} clubs, {len(rows)} players above {min_minutes} minutes.",
        "", f"## {text['players_heading']}", "",
        _table(
            text["cols_player"],
            [
                [names.get(row["player_id"], row["player_id"]), row["team"],
                 row["grade"] or "-", row["position"] or "-", row["apps"], row["starts"],
                 row["minutes"], row["shots"], row["goals"],
                 f"{row['shots_per_90']:.2f}", f"{row['conversion']:.3f}"]
                for row in rows[:top]
            ],
            left=4,
        ),
        "", text["players_note"].format(minutes=min_minutes),
    ]

    team = matrix_team or profile[0]["team_pk"]
    team_name = next((row["team"] for row in profile if row["team_pk"] == team), "")
    grid = analysis.minutes_matrix(conn, series_id, team)
    if grid["players"]:
        headers = ["Player", "Yr", "Pos"] + [str(s) for s in grid["sections"]] + ["Total"]
        body = []
        for player in grid["players"]:
            body.append(
                [names.get(player["player_id"], player["player_id"]), player["grade"] or "-",
                 player["position"] or "-"]
                + [player["minutes"].get(section, "") or "" for section in grid["sections"]]
                + [player["total"]]
            )
        parts += ["", f"## {text['minutes_heading']} — {team_name}", "",
                  _table(headers, body, left=3), "", text["minutes_note"]]

    parts += ["", f"## {text['reproduce']}", "", "```bash",
              "togakuren sample --out docs/PLAYER_ANALYSIS_SAMPLE.md", "```", ""]
    return "\n".join(parts)
